### ISSUE TITLE
Update-URLs in plugin.cfg are not a raw cfg file

### ISSUE THREAD

**Issue by christianTF** [ingenarius/LoxBerry-Plugin-synology-v2#1]
https://github.com/ingenarius/LoxBerry-Plugin-synology-v2/blob/895ed449f958d9e84f5777fed10223d0c2d5aebe/plugin.cfg#L43

The hyperlinks in RELEASECFG= and PRERELEASECFG= do not link raw .cfg files of update location, but to the github webinterface showing the plugin.cfg itself.

The links need to be:
`https://raw.githubusercontent.com/ingenarius/LoxBerry-Plugin-synology-v2/master/release.cfg`
`https://raw.githubusercontent.com/ingenarius/LoxBerry-Plugin-synology-v2/master/prerelease.cfg`
(btw prerelease.cfg currently not existing)

The current wrong hyperlinks break LoxBerry AutoUpdate - will be fixed in LB2.0.1 (https://github.com/mschlenstedt/Loxberry/issues/1110)

To fix the issue for plugin users, users cannot use AutoUpdate, but need to manually update the Synology-Plugin to a fixed version.

**Comment by ingenarius** [comment]
I fixed this issue. Thx for your help!
